/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.pavinan.java.devextreme.helpers.datasource;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
