/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.pavinan.java.devextreme.helpers.datasource;

import org.junit.Test;
import static org.junit.Assert.*;

public class UnitTests {
    @Test public void test1() {        
    }
}
